# Generated by Django 3.2.3 on 2021-06-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChitietSach', '0023_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
